// Generated by CoffeeScript 1.6.3
(function() {
  var App, initialContainer,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  console.log("app loaded");

  navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;

  App = (function() {
    function App(ui) {
      this.ui = ui;
      this.getInitDataFromServer = __bind(this.getInitDataFromServer, this);
      this.start = __bind(this.start, this);
      this.urlId = null;
      this.pageId = window.location.toString().split("?")[1].split("=")[1];
      this.rawUrl = document.referrer;
      console.log(this.rawUrl);
    }

    App.prototype.start = function() {
      return this.getInitDataFromServer();
    };

    App.prototype.getInitDataFromServer = function() {
      return console.log("TODO do something.");
    };

    return App;

  })();

  initialContainer = (function() {
    function initialContainer() {
      this.waitingForUsers = true;
    }

    initialContainer.prototype.start = function() {
      var $container, $videoContainer;
      $('#setup-instructions').addClass('animated slideInDown');
      $container = $('#sample-user-container');
      return $videoContainer = $("#video-container");
    };

    return initialContainer;

  })();

  $(document).ready(function() {
    var app, ui;
    ui = new initialContainer();
    ui.start();
    app = new App(ui);
    return app.start();
  });

}).call(this);
