// Generated by CoffeeScript 1.6.3
(function() {
  "This is a hack to avoid having to manually pre-compile the Handlebars templates.";
  var name, templateStr, _ref,
    _this = this;

  window.buildTemplates = function() {
    var handlebarsElems, messageFeedElem, recordMessageArea, recordMessageControls, setGroupAndUserArea, sidenoteAppContent;
    sidenoteAppContent = "\n<div class=\"sidenote-metadata-wrapper\">\n    <div class=\"user-name-wrapper\">\n        Hey there <span class=\"user-name\">(unknown)</span>,\n    </div>\n    <div class=\"group-name-wrapper\">\n        you're in the group <span class=\"group-name\">(none)</span>.\n    </div>\n    <div class=\"metadata-problem-instructions\">\n    <span class=\"change-user-group\">change name or group</span>\n    </div>\n</div>\n\n\n<div class=\"record-message-wrapper\">\n</div>\n\n<div class=\"messages-area-wrapper\">\n    <div class=\"messages-area\">\n        <div class=\"messages-area-title\">Messages</div>\n        <div id=\"messages-container\"></div>\n    </div>\n</div>\n\n\n<div class=\"group-feed-wrapper\">\n    <div class=\"group-feed-area\">\n        <div class=\"group-feed-area-title\">Recent group activity</div>\n        <div class=\"group-feed-container\"></div>\n    </div>\n</div>";
    setGroupAndUserArea = "<div class=\"set-group-and-user\">\n  <div><input type=\"text\" class=\"user-name-input\" placeholder=\"Name\"></div>\n  <div><input type=\"text\" class=\"group-name-input\" placeholder=\"Group\"></div>\n  <p>You'll share video messages within your group.</p>\n  <p>Try the group name <strong>CS247</strong>.</p>\n  <button class=\"done-inputting-info\">Done</button>\n  <div class=\"input-info-error\"> </div>\n</div\n\n";
    messageFeedElem = "<div class=\"message-feed-elem\">\n  {{user}} posted on <a href=\"{{rawUrl}}\" target=\"_blank\">{{rawUrl}}</a>\n</div>";
    recordMessageArea = "<div class=\"record-message-area\">\n    <div class=\"record-message-container\">\n        <button class=\"record-button\">Record a message</button>\n        <div class=\"webcam_stream_container\">\n          <div id=\"webcam_stream\">\n              <div id=\"sample-user-container\">\n                <div id=\"sharing-video-help\" style=\"display:none\">\n                    <p>Click \"Share Selected Devices\" to use our video chat.</p>\n                    <div class=\"sample-user place-user\">\n                        <img class=\"allow\" src=\"../bookmarklet/library/allow-me.png\" alt=\"allow me\" width=\"300\" \>\n                    </div>\n                </div>\n              </div>\n          </div>\n        </div>\n        <div class=\"record-controls-wrapper\"></div>\n    </div>\n</div>";
    recordMessageControls = "<div class=\"record-message-controls-container\">\n  <button class=\"record-start-button\">Start</button>\n  <button class=\"record-stop-button\">Done, post!</button>\n  <button class=\"record-bail-button\">Oops, discard.</button>\n  <p>Recordings can be max 30 seconds.</p>\n  <span class=\"record-overtime-error-message\"></span>\n</div>";
    handlebarsElems = {
      "sidenoteAppContent": sidenoteAppContent,
      "setGroupAndUserArea": setGroupAndUserArea,
      "recordMessageArea": recordMessageArea,
      "recordMessageControls": recordMessageControls,
      "messageFeedElem": messageFeedElem
    };
    return handlebarsElems;
  };

  window.Templates = {};

  _ref = window.buildTemplates();
  for (name in _ref) {
    templateStr = _ref[name];
    window.Templates[name] = Handlebars.compile(templateStr);
  }

}).call(this);
