// Generated by CoffeeScript 1.6.3
(function() {
  "This is a hack to avoid having to manually pre-compile the Handlebars templates.";
  var name, templateStr, _ref,
    _this = this;

  window.buildTemplates = function() {
    var handlebarsElems, messageFeedElem, recordMessageArea, recordMessageControls, setGroupAndUserArea, sidenoteAppContent;
    sidenoteAppContent = "\n<div class=\"sidenote-metadata-wrapper\">\n    <div class=\"group-name-wrapper\">\n        Your group is <span class=\"group-name\">(none)</span>\n    </div>\n    <div class=\"user-name-wrapper\">\n        and you are <span class=\"user-name\">(unknown)</span>\n    </div>\n    <div class=\"metadata-problem-instructions\">\n    <div class=\"change-user-group\">Change?</div>\n    </div>\n</div>\n\n<div class=\"record-message-wrapper\">\n</div>\n\n<div class=\"messages-area-wrapper\">\n    <div class=\"messages-area\">\n        <div class=\"messages-area-title\">Website messages from group</div>\n        <div id=\"messages-container\"></div>\n    </div>\n</div>\n\n\n<div class=\"group-feed-wrapper\">\n    <div class=\"group-feed-area\">\n        <div class=\"group-feed-area-title\">Recent group activity</div>\n        <div class=\"group-feed-container\"></div>\n    </div>\n</div>";
    setGroupAndUserArea = "<div class=\"set-group-and-user\">\n  <div>Name? <input type=\"text\" class=\"user-name-input\" placeholder=\"What's your name?\"></div>\n  <div>Group? <input type=\"text\" class=\"group-name-input\" placeholder=\"Name your group!\"></div>\n  <p>You can share video messages with anybody in this group. Use the same group as a friend, or\n  come up with a new name and share it with friends.</p>\n  <p>You need to have cookies enabled to save your group info.</p>\n  <button class=\"done-inputting-info\">Done!</button>\n  <div class=\"input-info-error\"> </div>\n</div\n\n";
    messageFeedElem = "<div class=\"message-feed-elem\">\n  New message from {{user}} at <a href=\"{{rawUrl}}\" target=\"_blank\">{{rawUrl}}</a>\n</div>";
    recordMessageArea = "<div class=\"record-message-area\">\n    <div class=\"record-message-container\">\n        <div class=\"webcam_stream_container\">\n          <div id=\"webcam_stream\">\n              <div id=\"sample-user-container\">\n                  <div class=\"sample-user place-user\">\n                      <i class=\"fa fa-user\"></i>\n                  </div>\n              </div>\n          </div>\n        </div>\n        <button class=\"record-button\">Record a message for this site</button>\n        <div class=\"record-controls-wrapper\">\n        </div>\n    </div>\n</div>";
    recordMessageControls = "<div class=\"record-message-controls-container\">\n  <button class=\"record-start-button\">Start new recording (max 30 seconds)</button>\n  <button class=\"record-stop-button\">Done, post message!</button>\n  <button class=\"record-bail-button\">Oops, bail out.</button>\n  <span class=\"record-overtime-error-message\"></span>\n</div>";
    handlebarsElems = {
      "sidenoteAppContent": sidenoteAppContent,
      "setGroupAndUserArea": setGroupAndUserArea,
      "recordMessageArea": recordMessageArea,
      "recordMessageControls": recordMessageControls,
      "messageFeedElem": messageFeedElem
    };
    return handlebarsElems;
  };

  window.Templates = {};

  _ref = window.buildTemplates();
  for (name in _ref) {
    templateStr = _ref[name];
    window.Templates[name] = Handlebars.compile(templateStr);
  }

}).call(this);
