// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  $(document).ready(function() {
    return document.cookie = 'groupname=testgroupthing; expires=Thu, 2 Aug 2015 20:47:11 UTC; path=/';
  });

}).call(this);
